version: '3'

services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - '5432:5432'
      - '15432:15432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/coffee_assistant.init.sql
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=coffee_user
      - POSTGRES_DB=coffee
  coffee_assistant:
    image: coffee_assistant
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgresql
